<?php

/**
 *  Odstránenie sekcie pre komentáre z admin menu
 */

add_action('admin_menu', 'rich_burger_edit_comment_menu', 11);
function rich_burger_edit_comment_menu()
{
    remove_menu_page('edit-comments.php');
}

/**
 *  Odstránenie sekcie pre príspevky z admin menu
 */

add_action('admin_menu', 'rich_burger_edit_menu', 11);
function rich_burger_edit_menu()
{
    remove_menu_page('edit.php');
}

/**
 *  Odstránenie wordpressom pridávaného obsahu ktorý nepotrebujeme
 */

add_action('init', 'lans_embeds_init', 15);
function lans_embeds_init()
{
    // Odstraňuje "Generated by WordPress" tag
    remove_action('wp_head', 'wp_generator');

    // Odstraňuje RSS feed pre blog
    remove_action('wp_head', 'feed_links_extra', 3);
    remove_action('wp_head', 'feed_links', 2);

    // Odstraňuje RSD link
    remove_action('wp_head', 'rsd_link');

    // Tieto tri deklarácie odstraňujú REST API
    remove_action('wp_head', 'rest_output_link_wp_head');
    remove_action('wp_head', 'wp_oembed_add_discovery_links');
    remove_action('template_redirect', 'rest_output_link_header', 11);

    // Odstraňuje WLW Manifest link
    remove_action('wp_head', 'wlwmanifest_link');

    // Odstraňuje shortlink
    remove_action('wp_head', 'wp_shortlink_wp_head');
}
